# Generated by Django 4.2.3 on 2023-07-28 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('isActive', models.BooleanField(default=False)),
                ('groupId', models.CharField(default=1, max_length=40)),
                ('createdBy', models.CharField(default=1, max_length=50)),
                ('updatedBy', models.CharField(default=1, max_length=50)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('stateId', models.AutoField(primary_key=True, serialize=False)),
                ('stateName', models.CharField(max_length=50)),
                ('isVerified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('isActive', models.BooleanField(default=False)),
                ('groupId', models.CharField(default=1, max_length=40)),
                ('createdBy', models.CharField(default=1, max_length=50)),
                ('updatedBy', models.CharField(default=1, max_length=50)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('cityId', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=70)),
                ('pincode', models.CharField(max_length=6)),
                ('description', models.CharField(max_length=100, null=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('stateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_by_state', to='api.state')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('isActive', models.BooleanField(default=False)),
                ('groupId', models.CharField(default=1, max_length=40)),
                ('createdBy', models.CharField(default=1, max_length=50)),
                ('updatedBy', models.CharField(default=1, max_length=50)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('areaId', models.AutoField(primary_key=True, serialize=False)),
                ('areaName', models.CharField(max_length=70)),
                ('areaMC', models.CharField(max_length=70, null=True)),
                ('landmark', models.CharField(max_length=100, null=True)),
                ('areaContactNumber', models.IntegerField(null=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('cityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GetAllAreaByCityId', to='api.city')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
