# Generated by Django 4.2.3 on 2023-08-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='businessNumber',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='website',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
